version: "3.3"

services:
  loki:
    image: grafana/loki:latest
    volumes:
      - /home/vagrant/loki/config.yml:/etc/promtail/local-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped 
    
