version: '3.7'
services:
  app:
    build:
      dockerfile: ./Dockerfile.app
    ports:
      - "8007:8080"
    restart: unless-stopped
    networks:
      - local_default

networks:
  local_default:
    external: true
