version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "8888:8888"
      - "13133:13133"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /home/vagrant/otpl/otel-collector-config.yaml:/etc/otel-collector-config.yaml 
    networks:
      - local_default

networks:
  local_default:
    external: true