receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"  # Expondo métricas para o Prometheus
  debug:
    verbosity: detailed
  otlp:
    endpoint: alloy-collector:4317
    tls:
      insecure: true


service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]  # Exportando métricas para o Prometheus
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]